client_config_backend: file
client_config:
    client_id: 970871849719-5o35j3rtfiqs03e3j04jkvqj20c35tti.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive